// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iaklhqqadcydcngeouvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlha2xocXFhZGN5ZGNuZ2VvdXZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwODYyMDQsImV4cCI6MjA3NjY2MjIwNH0.CaQGJY35gOYk2MjGQNexALFvWgkaIMq_ATztOMUrEmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});