// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bauxcwmwgtsltlztymnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhdXhjd213Z3RzbHRsenR5bW53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwODkyNjgsImV4cCI6MjA3NjY2NTI2OH0.7jfsQ0Mb7QZgzU5GIE3SqYFiILe7eiCGZ5edeVqYNSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});